@startuml
'https://plantuml.com/class-diagram

AppMain -> getSiteName
getSiteName -> fileWriter
fileWriter --> createHTML
fileWriter --> createCSS
fileWriter --> createJS
fileWriter -> success

abstract fileWriter{
    Boolean JS/CSS Directory Creation
    File new...
    folder.mkdir();
}

Class createHTML{
    write newHTML
    write(path);
}

Class createJS{
    write(JSpath);
}

Class createCSS{
    write(CSSpath);
}

abstract getSiteName{
    Scanner String;
}

class success{
    Junit5 Success;
}

class AppMain {
<list> Names;
int i,j;
String temp;
}

@enduml